[Sun Jul 04 11:40:44.845565 2021] [ssl:warn] [pid 1624] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jul 04 11:40:44.970572 2021] [ssl:warn] [pid 1625] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jul 04 11:40:44.971881 2021] [mpm_prefork:notice] [pid 1625] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1d mod_wsgi/4.7.1 Python/3.8 configured -- resuming normal operations
[Sun Jul 04 11:40:44.971904 2021] [core:notice] [pid 1625] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Sun Jul 04 12:04:11.911014 2021] [mpm_prefork:error] [pid 1625] AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting
[Sun Jul 04 14:19:40.774468 2021] [mpm_prefork:notice] [pid 1625] AH00169: caught SIGTERM, shutting down
[Sun Jul 04 14:19:41.205242 2021] [ssl:warn] [pid 13606] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jul 04 14:19:41.214698 2021] [ssl:warn] [pid 13607] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jul 04 14:19:41.216029 2021] [mpm_prefork:notice] [pid 13607] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1d mod_wsgi/4.7.1 Python/3.8 configured -- resuming normal operations
[Sun Jul 04 14:19:41.216054 2021] [core:notice] [pid 13607] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Sun Jul 04 14:19:46.221349 2021] [mpm_prefork:error] [pid 13607] AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting
[Sun Jul 04 14:19:47.905922 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082] mod_wsgi (pid=13611): Failed to exec Python script file '/opt/bitnami/projects/feelfreetocode/feelfreetocode/wsgi.py'.
[Sun Jul 04 14:19:47.905992 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082] mod_wsgi (pid=13611): Exception occurred processing WSGI script '/opt/bitnami/projects/feelfreetocode/feelfreetocode/wsgi.py'.
[Sun Jul 04 14:19:47.908357 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082] Traceback (most recent call last):
[Sun Jul 04 14:19:47.908448 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "/opt/bitnami/projects/feelfreetocode/feelfreetocode/wsgi.py", line 8, in <module>
[Sun Jul 04 14:19:47.908456 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]     application = get_wsgi_application()
[Sun Jul 04 14:19:47.908467 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "/opt/bitnami/python/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Sun Jul 04 14:19:47.908473 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]     django.setup(set_prefix=False)
[Sun Jul 04 14:19:47.908482 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "/opt/bitnami/python/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
[Sun Jul 04 14:19:47.908488 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sun Jul 04 14:19:47.908496 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "/opt/bitnami/python/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
[Sun Jul 04 14:19:47.908502 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]     self._setup(name)
[Sun Jul 04 14:19:47.908510 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "/opt/bitnami/python/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
[Sun Jul 04 14:19:47.908516 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]     self._wrapped = Settings(settings_module)
[Sun Jul 04 14:19:47.908524 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "/opt/bitnami/python/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
[Sun Jul 04 14:19:47.908530 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Jul 04 14:19:47.908549 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "/opt/bitnami/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
[Sun Jul 04 14:19:47.908555 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]     return _bootstrap._gcd_import(name[level:], package, level)
[Sun Jul 04 14:19:47.908563 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[Sun Jul 04 14:19:47.908571 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[Sun Jul 04 14:19:47.908580 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[Sun Jul 04 14:19:47.908589 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[Sun Jul 04 14:19:47.908597 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
[Sun Jul 04 14:19:47.908606 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Sun Jul 04 14:19:47.908615 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]   File "/opt/bitnami/projects/feelfreetocode/feelfreetocode/settings.py", line 7, in <module>
[Sun Jul 04 14:19:47.908620 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082]     from dotenv import load_dotenv
[Sun Jul 04 14:19:47.908639 2021] [wsgi:error] [pid 13611] [client 117.247.153.221:62082] ModuleNotFoundError: No module named 'dotenv'
[Sun Jul 04 14:19:55.377552 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153] mod_wsgi (pid=13612): Failed to exec Python script file '/opt/bitnami/projects/feelfreetocode/feelfreetocode/wsgi.py'.
[Sun Jul 04 14:19:55.377634 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153] mod_wsgi (pid=13612): Exception occurred processing WSGI script '/opt/bitnami/projects/feelfreetocode/feelfreetocode/wsgi.py'.
[Sun Jul 04 14:19:55.378315 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153] Traceback (most recent call last):
[Sun Jul 04 14:19:55.378381 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "/opt/bitnami/projects/feelfreetocode/feelfreetocode/wsgi.py", line 8, in <module>
[Sun Jul 04 14:19:55.378389 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]     application = get_wsgi_application()
[Sun Jul 04 14:19:55.378399 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "/opt/bitnami/python/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Sun Jul 04 14:19:55.378405 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]     django.setup(set_prefix=False)
[Sun Jul 04 14:19:55.378413 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "/opt/bitnami/python/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
[Sun Jul 04 14:19:55.378419 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sun Jul 04 14:19:55.378428 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "/opt/bitnami/python/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
[Sun Jul 04 14:19:55.378433 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]     self._setup(name)
[Sun Jul 04 14:19:55.378441 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "/opt/bitnami/python/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
[Sun Jul 04 14:19:55.378446 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]     self._wrapped = Settings(settings_module)
[Sun Jul 04 14:19:55.378454 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "/opt/bitnami/python/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
[Sun Jul 04 14:19:55.378469 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Jul 04 14:19:55.378478 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "/opt/bitnami/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
[Sun Jul 04 14:19:55.378483 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]     return _bootstrap._gcd_import(name[level:], package, level)
[Sun Jul 04 14:19:55.378492 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[Sun Jul 04 14:19:55.378500 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[Sun Jul 04 14:19:55.378509 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[Sun Jul 04 14:19:55.378518 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[Sun Jul 04 14:19:55.378526 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
[Sun Jul 04 14:19:55.378535 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Sun Jul 04 14:19:55.378544 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]   File "/opt/bitnami/projects/feelfreetocode/feelfreetocode/settings.py", line 7, in <module>
[Sun Jul 04 14:19:55.378549 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153]     from dotenv import load_dotenv
[Sun Jul 04 14:19:55.378567 2021] [wsgi:error] [pid 13612] [client 117.247.153.221:58153] ModuleNotFoundError: No module named 'dotenv'
